server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 200 # Maximum amount of worker threads.
      min-spare: 10 # Minimum amount of worker threads.
  error:
    path: /system/error

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mvc:
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"
    dispatch-trace-request: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL